name: Deploy to Local Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # 🔥 Важно: используем self-hosted runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and deploy
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 5000:5000 --name myapp ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest